version: '3.8'

services:
  web:
    image: smithforge:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smithforge_web
    ports:
      - "${PORT:-3001}:3001"
    volumes:
      - "${APPDATA:-./outputs}:/app/outputs"
      - "${APPDATA_INPUTS:-./inputs}:/app/inputs"
    environment:
      - NODE_ENV=production
      - PYTHONUNBUFFERED=1
      - PUID=${PUID:-99}
      - PGID=${PGID:-100}
      - TZ=${TZ:-Etc/UTC}
      - UMASK=${UMASK:-022}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "com.docker.compose.project=smithforge"
      - "com.docker.compose.service=web"
      - "com.docker.compose.version=2.0"
      - "net.unraid.docker.webui=http://[IP]:[PORT:3001]"
      - "net.unraid.docker.shell=/bin/bash"
      - "net.unraid.docker.icon=https://raw.githubusercontent.com/S1N4X/SmithForge/main/img/smithforge_logo_white_small_v2.gif"
      - "net.unraid.docker.description=SmithForge is a tool for seamlessly combining two 3MF models by overlaying and embedding a Hueforge model onto a base shape with automatic scaling, positioning, and precise intersection alignment."
